# couchdb-cloud-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: replace-by-kustomize
  name: couchdb-cloud-service
spec:
  type: NodePort
  ports:
    - port: 5984
      targetPort: 5984
      nodePort: 31444
  selector:
    app: replace-by-kustomize