---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devfest-embedded-device

commonLabels:
  app: couchdb-device

resources:
  - ./couchdb-device-deployment.yml
  - ./couchdb-device-service.yml

images:
  - name: couchdb
  - newName: couchdb
  - newTag: latest